Repository php-parallel-lint/PHP-Parallel-Lint, pull requests merged in 2022-02, with the labels that each got.

#88 Composer: differentiate between dev and no-dev files for autoloading
  composer.json
Labels: enhancement

#84 Docs: show all options in help and README
  README.md
  src/Application.php
  src/Settings.php
Labels: documentation

#91 Release version 1.3.2
  CHANGELOG.md
  src/Application.php
Labels: documentation

#92 ErrorFormatter: support PHP Console Highlighter 1.0.0
  CHANGELOG.md
  composer.json
  src/ErrorFormatter.php
  src/Output.php
Labels: enhancement

#99 Add --no-dev for create-project command in README
  README.md
Labels: documentation

#98 ErrorFormatter: fix error msg on last line of code snippet
  src/ErrorFormatter.php
Labels: bug
