Repository php-parallel-lint/PHP-Parallel-Lint, pull requests merged in 2024-03, with the labels that each got.

#152 GH Actions: update PHP version for PHAR boxing
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: Type: chores/QA

#158 GH Actions: version update for various predefined actions
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: Type: chores/QA

#154 [PHP 8.4] Fixes for implicit nullability deprecation
  src/Manager.php
Labels: Type: chores/QA

#156 OutputTest: fix risky test
  tests/Unit/Outputs/OutputTest.php
Labels: Type: chores/QA

#160 Composer: add keywords
  composer.json
Labels: Type: documentation

#146 Skip shebang sequence if it is the first line
  bin/skip-linting.php
  tests/Unit/ParallelLintLintTest.php
  tests/fixtures/fixture-07/example.php
Labels: Type: enhancement

#159 GH Actions: fix duplicate release
  .github/workflows/release.yml
Labels: Type: chores/QA
